### ISSUE TITLE
SnowflakePS.format.ps1xml not signed

### ISSUE THREAD

**Issue by easyas314** [Snowflake-Labs/sfsnowsightextensions#1]
This might be asking too much, but attempting to import this in PS, it complains about execution policy and exits. Without changing that policy, it would be nice if the file was digitally signed.

**Comment by sfc-gh-dodievich** [comment]
Yeah, this is definitely a nice to have with Powershell. I'll check out what is necessary to do it. Last I looked it was daunting to get the certs, but I'll look.

**Comment by afeld** [comment]
[Workaround to temporarily bypass that policy](https://caiomsouza.medium.com/fix-for-powershell-script-not-digitally-signed-69f0ed518715)

**Comment by sfc-gh-mjohnson** [comment]
@sfc-gh-mybarra Is this workaround something you want to add to the ReadMe?

**Comment by sfc-gh-mybarra** [comment]
closing issue as we will not be able to complete this request
