### ISSUE TITLE
Option to not wait for completion on saved Dashboard worksheet executions

### ISSUE THREAD

**Issue by sfc-gh-satherton** [Snowflake-Labs/sfsnowsightextensions#23]
Referring to this processes toward the end of a dashboard save:
```
Running new Worksheet Storage CPU % (1Alca3n1G7v)
Query 01a6077a-0605-ba08-001e-030906f4042f at 8/3/2022 12:26:15 AM succeeded
```
I believe starting the worksheet execution and then moving on to the next without waiting would still function to update the worksheet queries Snowsight will use in the dashboard.  I would be OK if this feature also means that worksheet errors are not surfaced upon save.  It would be useful in situations where the dashboard template is already tested and known to work, but then it must be cloned many times for different target schemas/etc.

**Comment by sfc-gh-mybarra** [comment]
Hello @sfc-gh-satherton, thank you for filing this issue. As of now, there is no roadmap to develop around the functionality that you are requesting. The core use case of Import/Export will continue to be the primary focus of snowsightextensions. However, your suggestion will be revisited if we decide to add more features/updates.
