### ISSUE TITLE
About solutions to manage sharing of worksheets, folders, and dashboards

### ISSUE THREAD

**Issue by syama666** [Snowflake-Labs/sfsnowsightextensions#25]
Hi

I use this tool to manage snowsight, thank you.
Do you have a roadmap for implementing the ability to manage folder and worksheet sharing?
Managing 100 members manually is too much work, so I want to manage it with a script.

best regards.

**Comment by sfc-gh-rbacastow** [comment]
Hi @syama666, thanks for the callout/suggestions. While we share the same wish re: more seamlessly managing code across users via an api, as of now there is not a roadmap to develop around the sharing of worksheets/folders using this repo particularly. The repo does allow for the uploading of worksheets/dashboards to users which you have the credentials for, but it is not slated to be updated with the ability to go cross-user or upload to specific folders at this time as those snowsight endpoints are not exposed in a fashion which the CLI can reach them.
