### ISSUE TITLE
Saved <report_Name>.pdf file des not open in Adobe Reader. Gives  ERROR: can't find PDF header

### ISSUE THREAD

**Issue by dodaka** [Snowflake-Labs/sfsnowsightextensions#26]
Hi Daniel,
 
As per your article, I installed  Snowflake Extensions, and I was able to download one of my Snowsight Dashboards, and save it as a pdf file. However,  I am unable to open saved pdf file using Adobe Acrobat Reader.
I am getting the following error message:
 "Adobe Acrobat Reader could not open <Dashboard_Name>.pdf” because it is either not 
a supported file type or because the file has been damaged (for example, it was sent as an email attachment and wasn’t correctly decoded).

Next, I tried to fix the saved .pdf file by navigating to the following URL: https://cloudconvert.com/pdf-converter
and tried to convert from PDF to PDF. This time I received the following error message: 
"ERROR can't find PDF header"

This is the power shell (pwsh) command I used to create the pdf file:
$dashboards[0].SaveToFile("./MyDashboards/<Dashboard_Name>.pdf")
Saved C:\Users\<User_Name>\MyDashboards\ Dashboard_Name>.pdf

Please advise.
Thank you

**Comment by sfc-gh-mybarra** [comment]
@dodaka pdf export functionality is not native to Powershell. I've seen references to modules that can do this for you. I have also seen references to using pdf printer services, but that is outside the scope of this repo.
