### ISSUE TITLE
API limit reduced to 500

### ISSUE THREAD

**Issue by aryder-alogic** [Snowflake-Labs/sfsnowsightextensions#28]
GetWorksheets() and GetDashboards() requests are setting an explicit limit of 1000 in the optionsParam. These requests are returning BadRequest errors: {"error":{"message":"limit may not be less than 0 or greater than 500"}}. So it appears that the API has reduced the limit to 500. Changing the limit to 500 fixes the problem.

**Comment by tom-cn** [comment]
+1 for this

**Comment by sfc-gh-mybarra** [comment]
@aryder-alogic is this a hard daily limit? Or is it per session? A user reached out and stated that they receive the following error when they use the Invoke-SFDashboards command.
The error is: Invalid response from listing Dashboard entities

**Comment by sfc-gh-mybarra** [comment]
@tom-cn @aryder-alogic I approved the pull request and published a new release. Thank you for submitting the issue and assisting with the update to the code.
