### ISSUE TITLE
Wrong value for the OAuthNonce logged into debug output 

### ISSUE THREAD

**Issue by danielodievich** [Snowflake-Labs/sfsnowsightextensions#30]
I made a mistake which parameter I logged for the OAuthNonce.

In https://github.com/Snowflake-Labs/sfsnowsightextensions/blob/main/Commands/Authentication/ConnectAppCommand.cs#L301 currently:
```cs
                logger.Info("OAuthNonce={0}", deploymentSnowSightClientIDRedirectResult.Item1);
```
should be
```cs
                // The nonce gets passed from the cookie
                logger.Info("OAuthNonce={0}", deploymentSnowSightClientIDRedirectResult.Item2);
```

**Comment by sfc-gh-mybarra** [comment]
Thanks, Daniel. I made the update. I will be creating a new release shortly.
