### ISSUE TITLE
PS Module version does not match the Assembly Version

### ISSUE THREAD

**Issue by danielodievich** [Snowflake-Labs/sfsnowsightextensions#31]
For tidy-ness reasons, https://github.com/Snowflake-Labs/sfsnowsightextensions/blob/main/SnowflakePS.psd1#L30 needs to be kept in sync with the assembly version in the .csproj file.

**Comment by sfc-gh-mybarra** [comment]
Thanks! I knew that I forgot to update some parts of the files. I appreciate you.
