### ISSUE TITLE
Update the ReadMe and simplify process for repeated sign in

### ISSUE THREAD

**Issue by basilcea** [Snowflake-Labs/sfsnowsightextensions#34]
The subheading for Create New SFFilters is misleading as it mentions Create New Worksheets but the command below is to create new filters. Also i think using a powershell profile would simplify the step of logging in instead of each time having to import the module. 

I have created a pull request for this changes [here](https://github.com/Snowflake-Labs/sfsnowsightextensions/pull/36).

**Comment by sfc-gh-mybarra** [comment]
Thanks @basilcea . I have updated the ReadMe.
