### ISSUE TITLE
Update Read Me

### ISSUE THREAD

**Issue by basilcea** [Snowflake-Labs/sfsnowsightextensions#39]
- I added a pull request to add a shorter way to start snowsightextensions. Instead of having to Import-Module every time a sessions closes, you can easily  call ``$appContext = snowsightext`` on powershell.
- Also a section on how to test your local development is added to the readme

@sfc-gh-mybarra, i raised a pull request [here](https://github.com/Snowflake-Labs/sfsnowsightextensions/pull/38)

I hope this helps others.

**Comment by sfc-gh-mybarra** [comment]
Closing this issue as we will not be able to fulfill your request.
