### ISSUE TITLE
Sync Local Worksheets actions with Remote

### ISSUE THREAD

**Issue by basilcea** [Snowflake-Labs/sfsnowsightextensions#41]
I noticed that when i try to remove worksheets from remote it removes it but does not remove the local file on my folder. I think this feature would help greatly with version control especially using git.

@sfc-gh-mybarra I raised a [pull request](https://github.com/Snowflake-Labs/sfsnowsightextensions/pull/40) for this addition.

**Comment by sfc-gh-mybarra** [comment]
I am adding this as an enhancement request. We may not accept the pull request at this time, but hang in there. We appreciate your input.

**Comment by sfc-gh-mybarra** [comment]
closing this issue as we will not be able to fulfill this request.
