### ISSUE TITLE
Update documentation for New-SFDashboard

### ISSUE THREAD

**Issue by Postoronnik** [Snowflake-Labs/sfsnowsightextensions#48]
Documentation of how to create a new Dashboard in the description part for the parameter`ActionIfExists` is missing the value `Overwrite`. 
In the code, I found the part with the implementation for this case.

**Comment by Postoronnik** [comment]
If this functionality is somehow not working, please leave a comment about this.
It would be useful for me if it is working as I think, as it will make my work pretty easier.

**Comment by sfc-gh-mybarra** [comment]
@Postoronnik thanks opening the issue. I'll update the read me.

**Comment by sfc-gh-mybarra** [comment]
@Postoronnik have you tried to use `Overwrite`? That is not a valid option for Dashboards.

**Comment by Pavlo-Tymoshenko-Imprivata** [comment]
@sfc-gh-mybarra Actualy, I'm using it now for updating Dashboards and it is working completely fine.

**Comment by Postoronnik** [comment]
@sfc-gh-mybarra Yes, I'm using the `Overwrite` option for Dashboards importing and it is working well.
Actually, this option is crucial for me as it saves data about whom it was shared and with which type(`Edit`,``View + Run,`View`).
It's a cool feature because I have a flow where on one account we are creating and testing Dashboards, and on another account level, we are only importing the user that will save it and will share it with others.
