### ISSUE TITLE
 Invalid response from completing redirect OAuth Token for user

### ISSUE THREAD

**Issue by Pavlo-Tymoshenko-Imprivata** [Snowflake-Labs/sfsnowsightextensions#49]
```
Connect-SFApp -Account '**********.********.snowflakecomputing.com' 

cmdlet Connect-SFApp at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
UserName: **********
Password: *******************
Account '********' in region '********' is accessible at '***********************' and served by application server 'https://apps-api.c1.us-east-1.aws.app.snowflake.com' in main application 'https://app.snowflake.com'
Authenticating user ************************ in account *********** to Classic UI
Authenticating user ************************ in account *********** to Snowsight
Validating master token for user ************************ in account uia99484
Converting redirect token to authentication token for user ************************ in account ***********
Connect-SFApp: Invalid response from completing redirect OAuth Token for user
```
Last time I was using this script approximately two weeks ago and it was working fine.
In other issues I found pretty similar issue, but with the `clientId`.
Can this be fixed or the support of this lib is stopped?

**Comment by kangprog** [comment]
Please do not close this issue.

The value in the API request response from the OAuth_Complete_GetAuthenticationTokenFromOAuthRedirectToken function in SnowflakeDriver.cs looks strange.


In ConnectAppCommand.cs, there is a part that is filtered by regular expressions after the apiGET request.
```
Regex regexParameters = new Regex(@"(?i)var params = ({.*})", RegexOptions.IgnoreCase);
```


However, when I checked the actual value received in the apiGET response, it was different.
```
[TEST0] (<!doctype html><html><head><title>Snowflake</title><link rel="icon" type="image/png" href="/static/favicon-16.png" sizes="16x16"/><link rel="icon" type="image/png" href="/static/favicon-32.png" sizes="32x32"/><link rel="icon" type="image/png" href="/static/favicon-48.png" sizes="48x48"/><link rel="icon" type="image/png" href="/static/favicon-96.png" sizes="96x96"/><link rel="icon" type="image/png" href="/static/favicon-144.png" sizes="144x144"/><meta name="viewport" content="width=device-width"/><link rel="preload" href="/static/Inter-Black-c2edcb3c2d698b82baeb.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/static/Inter-Bold-3717db0be15085acc210.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/static/Inter-SemiBold-90c67f61a1c18b18a53c.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/static/Inter-Medium-be3029dd56c7701e7e9d.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/static/Inter-Regular-f80c55a7aedf386182e8.woff2" as="font" type="font/woff2" crossorigin></head><body><div id="reactRoot"></div><script defer="defer" src="/static/index.240305-3-aec5d9e0ad.js"></script></body></html>, oauth-nonce-kA9HfGXx=kA9HfGXxLAGVwWqa)
```


Is there a reason why the response from the api is different than what you expect?

**Comment by sfc-gh-mybarra** [comment]
@kangprog the last update came from another community member/user. If you would like to contribute and see if you can fix the authentication issue, you are welcome to.

**Comment by joshuataylor** [comment]
Also seeing the same thing, can't login with username and password or SSO.

If I had to take a guess, it would be part of the work they did to update federated authentication, and there was probably a change made recently.

I have been writing an implementation of the login process for another project, and last night I couldn't login to SSO, however username/password and private key both worked.

However today SSO is working again..

I believe that the login process for this app needs to be updated to reflect the exact fields that the browser sends, and do the exact authentication flow.

I'll take a look at it over the weekend.

**Comment by joshuataylor** [comment]
Okay, figured it out, what a pain:

1. Various URLs have changed, which means a few cookies have changed.
2. Authenticated endpoints now need `X-CSRF-Token` with the csrf token.
3. A few of the internal endpoints needed to have the actual properties in them now.

I've got it working in a branch, I'll commit it as a hotfix, but I would really like to push out a change I made that generalises cookie handling, so it's kept between requests in the AppUserContext, so that it's easier when things change, as cookies are one of those things you never want to hardcode unless you really, really need to.

**Comment by kangprog** [comment]
Thank you for looking at the issue. @joshuataylor 

You have cloned and run the commit hotfix branch, but SSO and ID/PW methods do not log in.
- https://github.com/joshuataylor/sfsnowsightextensions/tree/hotfix/get-cookies-from-redirect

The cosole log appears the same as before, as shown below. (same ID/PW auth)
```
Connect-SFApp: Invalid response from completing redirect OAuth Token for user
```

Is the branch I referenced the correct version?

**Comment by sfc-gh-mybarra** [comment]
@joshuataylor I reviewed the pull request from the branch feature/diagnostic-logging-fixes. I built the project and tried running the binaries. I received a message "waiting on debugger" which kept running. I ultimately had to kill the terminal.
