### ISSUE TITLE
Filter variable is not set when copying dashboard in another account

### ISSUE THREAD

**Issue by gvergnolle** [Snowflake-Labs/sfsnowsightextensions#51]
Hey,

I extracted a dashboard using:

```
$dashboards = Get-SFDashboards -AuthContext $appContext1
$dashboards[5] | ConvertTo-JSON -Depth 10 | Out-File "dashboards/my_dashboard.json"
```

Then loaded it into another account:

```
New-SFDashboard -AuthContext $appContext2 -DashboardFile 'dashboards/my_dashboard.json' -ActionIfExists CreateNew
```

The copy was successful but received a bunch of errors in the "Running new Worksheet" part:
```
Query 01b3678c-3201-287d-0015-************** at 4/2/2024 5:48:24 PM failed with Error: Bind variable :agency_instance_uuid not set.
```

As a consequence, the dashboard appears in my new account but all tiles show:
<img width="831" alt="image" src="https://github.com/Snowflake-Labs/sfsnowsightextensions/assets/47532124/852c6138-b3a4-4ec2-9f6d-120a7d76b0dc">

Though, all my filters are set properly.

Even weirder, when I manually edit the query and run it, the query runs without problem.

Any hint what is going on? It seems to be related to the filter not being set at the moment the dashboard is being copied.

Note: when I re-run the whole notebook, the error persists. It only goes away when opening each tile and running it from there, which is extremely cumbersome.

**Comment by sfc-gh-mybarra** [comment]
What do you mean by re-run the notebook? Do you mean to say that you click the blue Run button and the issue persists?

There is an Invoke-Dashboard module that might help. You could try importing the dashboard and then invoking it. Technically the dashboard tiles are getting invoked on import, but it's worth trying.

Regrettably, this repo is being deprecated. No further work is being done on this tool.

**Comment by gvergnolle** [comment]
Both re-running with the blue Run button and the invoke commands didn't work. The error persist
